import 'package:flutter/foundation.dart';

/// How the worker tile selection was made.
enum WorkerSelectionMode { preset, manual }

/// Predefined worker tile presets.
enum WorkerPresetType {
  /// Only base game worker tiles (no new tiles added).
  baseOnly,

  /// Replace 4× 1-1-1-1 base tiles with the 4 new Diamante distributions.
  /// Total per player stays at 11.
  replaceWithNew,

  /// Add only the 0-0-0-4 tile to the 11 base tiles.
  /// Total per player becomes 12. Community-recommended (BGG).
  baseWith0004,

  /// Add all 4 new Diamante tiles on top of the 11 base tiles.
  /// Total per player becomes 15.
  addAll,
}

/// Represents the user's worker tile selection for Module D (The New Workers).
///
/// When [mode] is [WorkerSelectionMode.preset], the selection is determined
/// by [presetType]. When [mode] is [WorkerSelectionMode.manual],
/// [tileQuantities] contains the per-player quantity for each distribution.
class WorkerSelectionEntity {
  const WorkerSelectionEntity({
    this.mode = WorkerSelectionMode.preset,
    this.presetType = WorkerPresetType.addAll,
    this.tileQuantities = const {},
    this.isSurprise = false,
  });

  final WorkerSelectionMode mode;
  final WorkerPresetType presetType;

  /// Map of tile distribution name → quantity per player.
  ///
  /// Example: `{"1-1-1-1": 4, "2-1-0-1": 5, "0-0-0-4": 1, ...}`.
  /// Only used when [mode] == [WorkerSelectionMode.manual].
  final Map<String, int> tileQuantities;

  /// Whether this manual selection was generated by the "Surprise +2"
  /// random action. Display-only: lets the UI label it "Surprise"
  /// instead of "Manual".
  final bool isSurprise;

  /// Base game worker tile distributions with their default quantities.
  static const Map<String, int> baseDistributions = {
    '1-1-1-1': 4,
    '2-1-0-1': 5,
    '3-0-0-1': 1,
    '3-1-0-0': 1,
  };

  /// New Diamante worker tile distributions with their default quantities.
  static const Map<String, int> newDistributions = {
    '0-0-0-4': 1,
    '0-0-2-2': 1,
    '0-2-0-2': 1,
    '0-1-0-3': 1,
  };

  /// Computes the effective tile quantities for this selection.
  ///
  /// Returns a map of distribution name → quantity per player,
  /// regardless of whether this is a preset or manual selection.
  Map<String, int> get effectiveQuantities {
    if (mode == WorkerSelectionMode.manual) {
      return tileQuantities;
    }
    return switch (presetType) {
      WorkerPresetType.baseOnly => {...baseDistributions},
      WorkerPresetType.replaceWithNew => {
        // Remove 4× 1-1-1-1, keep the rest, add 4 new
        '1-1-1-1': 0,
        '2-1-0-1': 5,
        '3-0-0-1': 1,
        '3-1-0-0': 1,
        ...newDistributions,
      },
      WorkerPresetType.baseWith0004 => {...baseDistributions, '0-0-0-4': 1},
      WorkerPresetType.addAll => {...baseDistributions, ...newDistributions},
    };
  }

  /// Total number of worker tiles per player for this selection.
  int get tilesPerPlayer {
    return effectiveQuantities.values.fold(0, (sum, qty) => sum + qty);
  }

  WorkerSelectionEntity copyWith({
    WorkerSelectionMode? mode,
    WorkerPresetType? presetType,
    Map<String, int>? tileQuantities,
    bool? isSurprise,
  }) {
    return WorkerSelectionEntity(
      mode: mode ?? this.mode,
      presetType: presetType ?? this.presetType,
      tileQuantities: tileQuantities ?? this.tileQuantities,
      isSurprise: isSurprise ?? this.isSurprise,
    );
  }

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;

    return other is WorkerSelectionEntity &&
        other.mode == mode &&
        other.presetType == presetType &&
        other.isSurprise == isSurprise &&
        mapEquals(other.tileQuantities, tileQuantities);
  }

  @override
  int get hashCode => Object.hash(
    mode,
    presetType,
    isSurprise,
    // MapEntry has no value-based equality, so hash key/value pairs
    // explicitly (unordered, matching mapEquals semantics).
    Object.hashAllUnordered(
      tileQuantities.entries.map((e) => Object.hash(e.key, e.value)),
    ),
  );
}
